### ISSUE TITLE
我可以提交一些 PR 不？

### ISSUE THREAD

**Issue by Bian-Sh** [LiShengYang-yiyi/YIUI#1]
RT ,如果对自动化有改善的想法可以直接提 PR 不？

**Comment by LiShengYang-yiyi** [comment]
可以的
欢迎到群里讨论


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "LiShengYang-yiyi/YIUI"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年11月10日(星期五) 晚上6:25
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[LiShengYang-yiyi/YIUI] 我可以提交一些 PR 不？ (Issue #1)





 
RT ,如果对自动化有改善的想法可以直接提 PR 不？
