### ISSUE TITLE
ET8.1 YIUIBindProvider.Get() 应该可以直接通过CodeTypes获取

### ISSUE THREAD

**Issue by czwaxm** [LiShengYang-yiyi/YIUI#6]
public YIUIBindVo[] Get()
        {
            HashSet<Type> types = CodeTypes.Instance.GetTypes(typeof(YIUIAttribute));
            var binds = new List<YIUIBindVo>();
            foreach (var type in types)
            {
                var uiAttributes = (YIUIAttribute[])type.GetCustomAttributes(typeof(YIUIAttribute), true);
                foreach (var attribute in uiAttributes)
                {
                    if (GetBindVo(out var bindVo, attribute, type))
                    {
                        binds.Add(bindVo);
                    }
                }
            }

            return binds.ToArray();
        }
        不需要重复扫描程序集,效率是不是更高点?

**Comment by LiShengYang-yiyi** [comment]
那没运行时怎么办呢 不就GG了...
这个是编辑器用的
运行时又反射替代 所以不存在效率问题
