### ISSUE TITLE
关闭打开管理问题

### ISSUE THREAD

**Issue by Mr-sB** [LiShengYang-yiyi/YIUI#9]
关闭Panel A  触发关闭动画1
同一帧打开Panel B，  A B层级相同，A又被堆栈管理关闭了一次，触发关闭动画2
关闭动画1完成，执行对象大小复原操作， 执行对象销毁逻辑
关闭动画2完成，执行对象大小复原操作报错，因为对象已经被销毁了

这是设计bug，还是有什么考量？如何规避这个问题呢？

**Comment by LiShengYang-yiyi** [comment]
从已知内容上 Panel是有堆栈管理的
所以要尽可能的避免与堆栈管理冲突
你举的这个例子就是与堆栈管理冲突了
当然框架也需要设计一些防呆设计 防止出现这种情况
从最开始 开关都是没有锁的  又因为异步的原因所以经常出现这种问题
后来就在开关上加锁了不过是分别的  到现在ET9 已经对开关是panel层时加的相同锁

首先这个结果肯定是错误的  所以算BUG 但是不是设计BUG
有些东西没办法去规避 就像你举例的
明知Panel层是有堆栈管理的 又在异步过程中这样写 那肯定是有问题咯
就好像 异步加载一个预制体然后到某个节点下 但是你加载过程中你去吧那个节点删了
导致报错 你说这个算不算设计BUG

这些嘛只能尽可能的去避免 要么写的人水平高 要么框架上尽可能的去优化防呆
你说的这个问题ET9应该是不存在的

要避免 1. 知道这么写会错就不要这样写  2.参考ET9加锁

**Comment by Mr-sB** [comment]
1. 知道这样会错，但是不好避免。关闭A是一个模块执行的，打开B是另一个模块执行的。两个模块本来互不相关，如何优雅的处理等A关闭结束才能打开B呢？而且确实不应该把这种“问题”暴露给使用者
2. 用的main分支，还没看加锁的逻辑
3. ET分支能在非ET框架下使用吗？不能的话main分支是否要解决这个问题？

**Comment by LiShengYang-yiyi** [comment]
参考ET9 开关加相同锁就可以了

**Comment by Mr-sB** [comment]
建议官方能把这个功能从ET9中拆出来，作为一个新的分支。让用户去维护使用成本太大了，说实话不好维护

**Comment by LiShengYang-yiyi** [comment]
ET里面有的功能 通用版本不一定有 因为底层框架不一样
所以还是要看实际情况
高的版本当然有更多的维护和优化咯
如果每次高版本的东西都要移植到其他版本里面维护成本时间很高的
愿意的应该升级版本  或者自己去移植

**Comment by Mr-sB** [comment]
可是ETYIUI在非ET框架下不能使用啊。那意思是普通YIUI放弃维护咯？要使用高版本功能必须使用ET框架？

**Comment by LiShengYang-yiyi** [comment]
通用版本 就算要更新功能那也得有基础才行呀
比如假设..   你非要我在通用版更新个事件通知  我哪里去给你找这么个功能?
你这不是强人所难    再比如QQ 这么多版本 十几年前的你不可能也要让她给你吧现在有的功能给你加上吧

通用版会维护 但是也要在能力范围内
你提的这个不是BUG 是你自己写出来的 所以不会维护
在现有条件下你就是应该注意写法  如果你实在想要也给你思路了有参考

另外如果有条件 当然是推荐使用一个更全面的框架咯
在一个好的框架下 效率自然会提升
有能力当然推荐你用ET了

通用版只能算是入门非常简单的
